### ISSUE TITLE
PyPi Name Request

### ISSUE THREAD

**Issue by tombulled** [eriknw/innertube#1]
Hi @eriknw,

I recently tried to deploy my repository, [`innertube`](https://github.com/tombulled/innertube), to PyPi under the name `innertube`, however you currently own the package name.

As their appears to be no functionality to your package, and it appears to have been inactive for a while, please will you allow me to claim the name for my own package on PyPi.

Many thanks,

Tom

**Comment by tombulled** [comment]
Hi @eriknw,

As per your message in [pypa/pypi-support/issues/937](https://github.com/pypa/pypi-support/issues/937), I was wondering if you would please re-consider my request?

> @tombulled has made a reasonable request, and has been very courteous while doing so. If I fail to make much more progress with innertube this year, then I will happily and voluntarily relinquish the name on PyPI (but feel free to ping me again as you feel appropriate).

It's been a good few months now and I would really appreciate if you would allow me to claim the `innertube` package name.

All the best,

Tom

**Comment by eriknw** [comment]
I was just thinking about this.  Done.  You'd better go claim it! 🎁

**Comment by tombulled** [comment]
> I was just thinking about this.  Done.  You'd better go claim it! 🎁 

Thanks very much! You've made my day 🙏
